{% set name = "types-paramiko" %}
{% set version = "2.8.21" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-paramiko-{{ version }}.tar.gz
  sha256: 640c850aca8adc41b0d5a225ee36ac7812689e1a4370c312f8e4b92acec8e405

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - types-cryptography

test:
  commands:
    - test -f $SP_DIR/paramiko-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for paramiko
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
